name: Publish Image

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: apt-get update && apt-get install build-essential pkg-config libssl-dev -y
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo test

  publish-image:
    runs-on: ubuntu-latest
    needs: "test"
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: freshollie/hello-boys-bot
          tag_with_ref: true
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
