name: pipeline

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update && sudo apt-get install build-essential pkg-config libssl-dev -y
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo test

  build:
    runs-on: ubuntu-latest
    if: "!startsWith(github.ref, 'refs/tags/v')"

    steps:
      - uses: actions/checkout@v2
      - run: docker build -t hello-boys .

  build-and-publish:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    needs: "test"

    steps:
      - uses: actions/checkout@v2

      - name: Build and Publish head Docker image
        uses: VaultVulp/gp-docker-action@1.1.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: hello-boys
          extract-git-tag: true
